unique_ids:
  forms:
    init.aap_admin: GAI4JLG5H4HFWL6CP4276QRDOC7JGB7V
    init.Form2: T4YVE4ZFS6VEKXH6MORZOGVQJGJ4RO6N
    init.fin: KIZ2DP5TELNC53GN65SETKFJ54X5XDAT
    init.bal.RowTemplate2: 5E32JTBP3LFNRYJ5XV5I5OMHOKBUETD7
    init.verific: BGAQRFZQQTR6FEJHT4NDJIB723WBPUOP
    init: ETJ7H3NFPUD43GIT65ZTHTULRL3HVXGF
    Form1: YR3CXP6MHAXSJ7KVKC4QB34ZSIKPCXFJ
    init.bal: XUINKI5UKTMLBRPDRHJAWOFU5VFNWJ2L
    init.start: 27GJKF6OHOFDOWXMU63QRNXGJX2ZUOOZ
  modules:
    My_globals: 7WN3JUVW6PNPLZULATGKMCZZZ3Q7G77C
  server_modules:
    ServerModule1: MPLUV3QGPINJGQI4QW3SR4HMV3GP4KA5
  assets:
    standard-page.html: AXGMYXHKH7N2QSPELQUJ7WP2E2VQYDS2
    theme.css: SOCFCOEF6I4VUZBWL67I3MNLACKHBHKH
