unique_ids:
  forms:
    init.analiza: NIPARNQ4CEFK734DWT72FFT3W4BVZZAE
    init.crit: FLAAQCEZXLNKHYBQR62XBZTRYMR6QR4C
    init.fin: 527PRCFVWBB3OPQ5OSIZOTAWOH5NGGPD
    init.bal.RowTemplate2: IXD4MGBPP6WSODQP73CZN7BP4T5GP6B2
    init.verific: BGAQRFZQQTR6FEJHT4NDJIB723WBPUOP
    init: ETJ7H3NFPUD43GIT65ZTHTULRL3HVXGF
    init.st: RIYUULRZI7IEAGZ3ERSAPDDXPWNEOQET
    init.bal: XUINKI5UKTMLBRPDRHJAWOFU5VFNWJ2L
    init.verific.ItemTemplate1: TMH5S5KPAXTJ4EVJJW3ZVBL4HC5A3EW5
    init.st.ItemTemplate3: QUMKTCXJY2RHTMZWY3QYEVFLNWHUPWBY
  modules:
    My_globals: 7WN3JUVW6PNPLZULATGKMCZZZ3Q7G77C
    init.bal.refre: ZR7FUPHSZUL27AOSPHNTI2Y2IXC5AIPE
  server_modules:
    ServerModule1: MPLUV3QGPINJGQI4QW3SR4HMV3GP4KA5
    keysFyn: 4ESW7XLNPEX7GC6PUJE4ZFTCX2CRMJCX
    work: GD72UJ7K44DM34XM7D2JYMPNU4G7QYKF
  assets:
    standard-page.html: AXGMYXHKH7N2QSPELQUJ7WP2E2VQYDS2
    theme.css: SOCFCOEF6I4VUZBWL67I3MNLACKHBHKH
