unique_ids:
  forms:
    init.crit: FLAAQCEZXLNKHYBQR62XBZTRYMR6QR4C
    init.fin: KIZ2DP5TELNC53GN65SETKFJ54X5XDAT
    init.bal.RowTemplate2: IXD4MGBPP6WSODQP73CZN7BP4T5GP6B2
    init.Form3.RowTemplate1: SOGPWMOBEUPACPNJWBQ42KP6SOVFP7LK
    init.verific: BGAQRFZQQTR6FEJHT4NDJIB723WBPUOP
    init: ETJ7H3NFPUD43GIT65ZTHTULRL3HVXGF
    init.Form3: AGNHVYJFMWZPU7RH2FCKGISCOURQY5GW
    Form1: 666FPQYDBMHF453YTXACIZSL5CG26QXW
    init.bal: XUINKI5UKTMLBRPDRHJAWOFU5VFNWJ2L
    init.verific.ItemTemplate1: TMH5S5KPAXTJ4EVJJW3ZVBL4HC5A3EW5
    Form1.ItemTemplate2: YWWVCIRQHWIA3DZ5DGINBFPR2UELXFQQ
    init.start: 27GJKF6OHOFDOWXMU63QRNXGJX2ZUOOZ
  modules:
    My_globals: 7WN3JUVW6PNPLZULATGKMCZZZ3Q7G77C
    init.bal.refre: ZR7FUPHSZUL27AOSPHNTI2Y2IXC5AIPE
  server_modules:
    ServerModule1: MPLUV3QGPINJGQI4QW3SR4HMV3GP4KA5
    keysFyn: 4ESW7XLNPEX7GC6PUJE4ZFTCX2CRMJCX
  assets:
    standard-page.html: AXGMYXHKH7N2QSPELQUJ7WP2E2VQYDS2
    theme.css: SOCFCOEF6I4VUZBWL67I3MNLACKHBHKH
